[server]
port = 8501
address = "0.0.0.0"
headless = true
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#FFE600"
backgroundColor = "#0E1015"
secondaryBackgroundColor = "#181B22"
textColor = "#FFFFFF"
font = "sans serif"
